#!/usr/bin/env bash

# ==============================================================================
# NVIDIA RTX PASSTHROUGH SETUP FOR THE WINDOWS VM
# ==============================================================================
# This script prepares the host for VFIO passthrough of the NVIDIA RTX 3050
# and refreshes gpu_config.sh + start_win_vm_gpu.sh with the detected PCI IDs.
# ==============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VM_CONFIG_FILE="$SCRIPT_DIR/vm_config.sh"
GPU_CONFIG_FILE="$SCRIPT_DIR/gpu_config.sh"
GPU_START_SCRIPT="$SCRIPT_DIR/start_win_vm_gpu.sh"

if [ -f "$VM_CONFIG_FILE" ]; then
  # shellcheck disable=SC1090
  . "$VM_CONFIG_FILE"
fi

: "${VM_DIR:=$SCRIPT_DIR}"
: "${VM_NAME:=windows-vm}"
: "${VM_DISK_NAME:=windows10.qcow2}"
: "${VIRTIO_ISO_NAME:=virtio-win.iso}"
: "${WIN_ISO_NAME:=windows.iso}"
: "${VM_DISK_SIZE:=100G}"
: "${VM_RAM_MB:=12288}"
: "${VM_SMP_SOCKETS:=1}"
: "${VM_SMP_CORES:=4}"
: "${VM_SMP_THREADS:=2}"
: "${VM_RDP_PORT:=2222}"
: "${VM_NET_DEVICE:=e1000e}"

require_command() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "Perintah '$1' tidak ditemukan."
    exit 1
  fi
}

require_command lspci
require_command sudo
require_command awk
require_command sed
require_command mktemp

GPU_LINE="$(lspci -Dnn | awk 'tolower($0) ~ /nvidia/ && /(VGA compatible controller|3D controller)/ {print; exit}')"
GPU_AUDIO_LINE="$(lspci -Dnn | awk 'tolower($0) ~ /nvidia/ && /(Audio device|Audio controller)/ {print; exit}')"

if [ -z "$GPU_LINE" ] || [ -z "$GPU_AUDIO_LINE" ]; then
  echo "GPU NVIDIA atau fungsi audio NVIDIA tidak terdeteksi."
  echo "Pastikan RTX 3050 dan audio controller-nya ada di lspci."
  exit 1
fi

GPU_BDF="$(printf '%s\n' "$GPU_LINE" | awk '{print $1}')"
GPU_AUDIO_BDF="$(printf '%s\n' "$GPU_AUDIO_LINE" | awk '{print $1}')"
if [[ "$GPU_BDF" == *:*:* ]]; then
  GPU_BDF_SYS="$GPU_BDF"
else
  GPU_BDF_SYS="0000:${GPU_BDF}"
fi
if [[ "$GPU_AUDIO_BDF" == *:*:* ]]; then
  GPU_AUDIO_BDF_SYS="$GPU_AUDIO_BDF"
else
  GPU_AUDIO_BDF_SYS="0000:${GPU_AUDIO_BDF}"
fi
GPU_IDS="$(lspci -nn -s "$GPU_BDF" | awk -F'[][]' '{print $(NF-1)}')"
GPU_AUDIO_IDS="$(lspci -nn -s "$GPU_AUDIO_BDF" | awk -F'[][]' '{print $(NF-1)}')"

echo "NVIDIA GPU terdeteksi:"
echo "  - GPU:   $GPU_LINE"
echo "  - Audio: $GPU_AUDIO_LINE"
echo "  - PCI host GPU:   $GPU_BDF_SYS"
echo "  - PCI host audio: $GPU_AUDIO_BDF_SYS"

cat > "$GPU_CONFIG_FILE" <<EOF
#!/usr/bin/env bash

# GPU passthrough config for the Windows VM.
# This file is generated by gpu_passthrough_setup.sh.

GPU_MODE="nvidia"
GPU_NAME="NVIDIA RTX 3050 Mobile"
GPU_HOST_PCI="$GPU_BDF_SYS"
GPU_AUDIO_PCI="$GPU_AUDIO_BDF_SYS"
GPU_VENDOR_IDS="$GPU_IDS,$GPU_AUDIO_IDS"
GPU_USE_VIRTIO_DISPLAY="yes"
EOF

chmod +x "$GPU_CONFIG_FILE"
echo "Config GPU ditulis ke: $GPU_CONFIG_FILE"

if [ -f "$GPU_START_SCRIPT" ]; then
  chmod +x "$GPU_START_SCRIPT"
  echo "Script GPU tetap dipakai: $GPU_START_SCRIPT"
else
  echo "Script GPU tidak ditemukan: $GPU_START_SCRIPT"
  echo "Pastikan start_win_vm_gpu.sh ada di folder repo."
  exit 1
fi

normalize_grub_cmdline() {
  local line current cleaned backup tmp
  backup="/etc/default/grub.bak.$(date +%Y%m%d-%H%M%S)"
  sudo cp /etc/default/grub "$backup"

  line="$(grep '^GRUB_CMDLINE_LINUX_DEFAULT=' /etc/default/grub | head -n1 || true)"
  if [ -z "$line" ]; then
    echo "GRUB_CMDLINE_LINUX_DEFAULT tidak ditemukan di /etc/default/grub"
    exit 1
  fi

  current="$(printf '%s\n' "$line" | sed -n 's/^GRUB_CMDLINE_LINUX_DEFAULT="\(.*\)"$/\1/p')"
  if [ -z "$current" ]; then
    current="$(printf '%s\n' "$line" | sed -n "s/^GRUB_CMDLINE_LINUX_DEFAULT='\(.*\)'$/\1/p")"
  fi
  if [ -z "$current" ]; then
    current="${line#GRUB_CMDLINE_LINUX_DEFAULT=}"
  fi

  cleaned="$(printf '%s' "$current" | sed -E "s/GRUB_CMDLINE_LINUX_DEFAULT='([^']*)'/\1/g; s/GRUB_CMDLINE_LINUX_DEFAULT=\"([^\"]*)\"/\1/g; s/[\"']//g; s/[[:space:]]+/ /g; s/^ //; s/ $//")"
  cleaned="$(printf '%s\n' "$cleaned" | awk '
    {
      for (i = 1; i <= NF; i++) {
        if ($i ~ /^(intel_iommu=on|amd_iommu=on|iommu=pt|vfio-pci.ids=|nvidia_drm.modeset=)/) {
          next
        }
        out = out sep $i
        sep = " "
      }
    }
    END { print out }
  ')"

  if [ -n "$cleaned" ]; then
    cleaned="$cleaned intel_iommu=on iommu=pt vfio-pci.ids=$GPU_IDS,$GPU_AUDIO_IDS"
  else
    cleaned="intel_iommu=on iommu=pt vfio-pci.ids=$GPU_IDS,$GPU_AUDIO_IDS"
  fi

  tmp="$(mktemp)"
  awk -v replacement="GRUB_CMDLINE_LINUX_DEFAULT=\"$cleaned\"" '
    BEGIN { updated = 0 }
    /^GRUB_CMDLINE_LINUX_DEFAULT=/ && !updated {
      print replacement
      updated = 1
      next
    }
    { print }
    END {
      if (!updated) {
        print replacement
      }
    }
  ' /etc/default/grub > "$tmp"

  sudo cp "$tmp" /etc/default/grub
  rm -f "$tmp"

  echo "Backup GRUB dibuat: $backup"
  echo "GRUB_CMDLINE_LINUX_DEFAULT baru:"
  echo "  $cleaned"
}

update_mkinitcpio_modules() {
  local backup tmp
  backup="/etc/mkinitcpio.conf.bak.$(date +%Y%m%d-%H%M%S)"
  sudo cp /etc/mkinitcpio.conf "$backup"
  tmp="$(mktemp)"

  awk '
    BEGIN {updated=0}
    /^MODULES=/ && !updated {
      if ($0 ~ /vfio_pci/) {
        print
      } else {
        sub(/^MODULES=\(/, "MODULES=(vfio_pci vfio vfio_iommu_type1 ")
        print
      }
      updated=1
      next
    }
    { print }
    END {
      if (!updated) {
        print "MODULES=(vfio_pci vfio vfio_iommu_type1)"
      }
    }
  ' /etc/mkinitcpio.conf > "$tmp"

  sudo cp "$tmp" /etc/mkinitcpio.conf
  rm -f "$tmp"
}

echo "Menulis binding VFIO dan blacklist module..."
cat <<EOF | sudo tee /etc/modprobe.d/winvm-vfio.conf >/dev/null
options vfio-pci ids=$GPU_IDS,$GPU_AUDIO_IDS
EOF

cat <<'EOF' | sudo tee /etc/modprobe.d/winvm-blacklist-nvidia.conf >/dev/null
blacklist nouveau
blacklist nvidia
blacklist nvidia_drm
blacklist nvidia_modeset
blacklist nvidia_uvm
EOF

normalize_grub_cmdline
update_mkinitcpio_modules

echo "Membangun ulang initramfs..."
sudo mkinitcpio -P

echo "Membangun ulang grub.cfg..."
sudo grub-mkconfig -o /boot/grub/grub.cfg

echo
echo "Setup passthrough selesai."
echo "Langkah berikutnya:"
echo "  1. Reboot host Linux."
echo "  2. Jalankan: bash $GPU_START_SCRIPT"
echo "  3. Di Windows guest, install driver NVIDIA setelah boot."
echo
echo "Catatan:"
echo "  - Intel Iris Xe tetap dipakai host."
echo "  - Kalau port HDMI/DP di RTX dipakai host, kemungkinan tidak akan aktif setelah passthrough."
