#!/usr/bin/env bash

# ==============================================================================
# NVIDIA RTX PASSTHROUGH SETUP FOR THE WINDOWS VM
# ==============================================================================
# This script prepares the host for VFIO passthrough of the NVIDIA RTX 3050
# and refreshes gpu_config.sh + start_win_vm_gpu.sh with the detected PCI IDs.
# ==============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VM_CONFIG_FILE="$SCRIPT_DIR/vm_config.sh"
GPU_CONFIG_FILE="$SCRIPT_DIR/gpu_config.sh"
GPU_START_SCRIPT="$SCRIPT_DIR/start_win_vm_gpu.sh"

if [ -f "$VM_CONFIG_FILE" ]; then
  # shellcheck disable=SC1090
  . "$VM_CONFIG_FILE"
fi

: "${VM_DIR:=$SCRIPT_DIR}"
: "${VM_NAME:=windows-vm}"
: "${VM_DISK_NAME:=windows10.qcow2}"
: "${VIRTIO_ISO_NAME:=virtio-win.iso}"
: "${WIN_ISO_NAME:=windows.iso}"
: "${VM_DISK_SIZE:=100G}"
: "${VM_RAM_MB:=12288}"
: "${VM_SMP_SOCKETS:=1}"
: "${VM_SMP_CORES:=4}"
: "${VM_SMP_THREADS:=2}"
: "${VM_RDP_PORT:=2222}"
: "${VM_NET_DEVICE:=e1000e}"

require_command() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "Perintah '$1' tidak ditemukan."
    exit 1
  fi
}

require_command lspci
require_command sudo
require_command awk
require_command sed
require_command mktemp

GPU_LINE="$(lspci -Dnn | awk 'tolower($0) ~ /nvidia/ && /(VGA compatible controller|3D controller)/ {print; exit}')"
GPU_AUDIO_LINE="$(lspci -Dnn | awk 'tolower($0) ~ /nvidia/ && /(Audio device|Audio controller)/ {print; exit}')"

if [ -z "$GPU_LINE" ] || [ -z "$GPU_AUDIO_LINE" ]; then
  echo "GPU NVIDIA atau fungsi audio NVIDIA tidak terdeteksi."
  echo "Pastikan RTX 3050 dan audio controller-nya ada di lspci."
  exit 1
fi

GPU_BDF="$(printf '%s\n' "$GPU_LINE" | awk '{print $1}')"
GPU_AUDIO_BDF="$(printf '%s\n' "$GPU_AUDIO_LINE" | awk '{print $1}')"
if [[ "$GPU_BDF" == *:*:* ]]; then
  GPU_BDF_SYS="$GPU_BDF"
else
  GPU_BDF_SYS="0000:${GPU_BDF}"
fi
if [[ "$GPU_AUDIO_BDF" == *:*:* ]]; then
  GPU_AUDIO_BDF_SYS="$GPU_AUDIO_BDF"
else
  GPU_AUDIO_BDF_SYS="0000:${GPU_AUDIO_BDF}"
fi
GPU_IDS="$(lspci -nn -s "$GPU_BDF" | awk -F'[][]' '{print $(NF-1)}')"
GPU_AUDIO_IDS="$(lspci -nn -s "$GPU_AUDIO_BDF" | awk -F'[][]' '{print $(NF-1)}')"

echo "NVIDIA GPU terdeteksi:"
echo "  - GPU:   $GPU_LINE"
echo "  - Audio: $GPU_AUDIO_LINE"
echo "  - PCI host GPU:   $GPU_BDF_SYS"
echo "  - PCI host audio: $GPU_AUDIO_BDF_SYS"

cat > "$GPU_CONFIG_FILE" <<EOF
#!/usr/bin/env bash

# GPU passthrough config for the Windows VM.
# This file is generated by gpu_passthrough_setup.sh.

GPU_MODE="nvidia"
GPU_NAME="NVIDIA RTX 3050 Mobile"
GPU_HOST_PCI="$GPU_BDF_SYS"
GPU_AUDIO_PCI="$GPU_AUDIO_BDF_SYS"
GPU_VENDOR_IDS="$GPU_IDS,$GPU_AUDIO_IDS"
GPU_USE_VIRTIO_DISPLAY="yes"
EOF

chmod +x "$GPU_CONFIG_FILE"
echo "Config GPU ditulis ke: $GPU_CONFIG_FILE"

cat > "$GPU_START_SCRIPT" <<'EOF'
#!/usr/bin/env bash

# ==============================================================================
# WINDOWS VM LAUNCHER WITH NVIDIA GPU PASSTHROUGH
# ==============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VM_CONFIG_FILE="$SCRIPT_DIR/vm_config.sh"
GPU_CONFIG_FILE="$SCRIPT_DIR/gpu_config.sh"

if [ -f "$VM_CONFIG_FILE" ]; then
  # shellcheck disable=SC1090
  . "$VM_CONFIG_FILE"
fi

if [ -f "$GPU_CONFIG_FILE" ]; then
  # shellcheck disable=SC1090
  . "$GPU_CONFIG_FILE"
else
  echo "gpu_config.sh tidak ditemukan di: $GPU_CONFIG_FILE"
  echo "Jalankan gpu_passthrough_setup.sh dulu."
  exit 1
fi

: "${VM_DIR:=$SCRIPT_DIR}"
: "${VM_NAME:=windows-vm}"
: "${VM_DISK_NAME:=windows10.qcow2}"
: "${VIRTIO_ISO_NAME:=virtio-win.iso}"
: "${WIN_ISO_NAME:=windows.iso}"
: "${VM_DISK_SIZE:=100G}"
: "${VM_RAM_MB:=12288}"
: "${VM_SMP_SOCKETS:=1}"
: "${VM_SMP_CORES:=4}"
: "${VM_SMP_THREADS:=2}"
: "${VM_RDP_PORT:=2222}"
: "${VM_NET_DEVICE:=e1000e}"
: "${GPU_HOST_PCI:=0000:01:00.0}"
: "${GPU_AUDIO_PCI:=0000:01:00.1}"
: "${GPU_USE_VIRTIO_DISPLAY:=yes}"

VM_DISK="$VM_DIR/$VM_DISK_NAME"
VIRTIO_ISO="$VM_DIR/$VIRTIO_ISO_NAME"
WIN_ISO="$VM_DIR/$WIN_ISO_NAME"

mkdir -p "$VM_DIR"

if [ ! -f "$VM_DISK" ]; then
  echo "Virtual disk tidak ditemukan! Membuat baru..."
  qemu-img create -f qcow2 "$VM_DISK" "$VM_DISK_SIZE"
fi

if [ ! -f "$WIN_ISO" ]; then
  echo "ISO Windows tidak ditemukan: $WIN_ISO"
  echo "Letakkan installer Windows sebagai $VM_DIR/windows.iso"
  exit 1
fi

if [ ! -f "$VIRTIO_ISO" ]; then
  echo "VirtIO ISO tidak ditemukan: $VIRTIO_ISO"
  exit 1
fi

HOST_GPU_SYSFS="/sys/bus/pci/devices/$GPU_HOST_PCI"
if [ ! -e "$HOST_GPU_SYSFS" ]; then
  echo "Host GPU device tidak ditemukan di $HOST_GPU_SYSFS"
  echo "Cek kembali GPU_HOST_PCI di gpu_config.sh"
  exit 1
fi

HOST_GPU_DRIVER=""
if [ -L "$HOST_GPU_SYSFS/driver" ]; then
  HOST_GPU_DRIVER="$(basename "$(readlink -f "$HOST_GPU_SYSFS/driver")")"
fi

if [ "$HOST_GPU_DRIVER" != "vfio-pci" ]; then
  echo "Peringatan: $GPU_HOST_PCI masih terikat ke driver '$HOST_GPU_DRIVER'."
  echo "Passthrough akan gagal sampai GPU dibind ke vfio-pci dan host di-reboot."
fi

echo "Memulai Windows VM dengan NVIDIA passthrough..."
echo "  - GPU: ${GPU_NAME:-NVIDIA RTX 3050 Mobile} (${GPU_HOST_PCI})"
echo "  - Audio GPU: ${GPU_AUDIO_PCI}"
echo "  - CPU: $((VM_SMP_CORES * VM_SMP_THREADS)) vCPUs"
echo "  - RAM: ${VM_RAM_MB} MB"

QEMU_CMD=(
  qemu-system-x86_64
  -enable-kvm
  -name "${VM_NAME}-gpu",process="${VM_NAME}-gpu"
  -machine type=q35,accel=kvm
  -cpu host,hv_relaxed,hv_spinlocks=0x1fff,hv_vapic,hv_time,hv_vendor_id=genuineintel,kvm=off
  -smp "sockets=${VM_SMP_SOCKETS},cores=${VM_SMP_CORES},threads=${VM_SMP_THREADS}"
  -m "$VM_RAM_MB"
  -mem-prealloc
  -rtc base=localtime,clock=host
  -device pcie-root-port,id=pcie.1,bus=pcie.0,chassis=1
  -device ich9-ahci,id=sata
  -drive "file=${VM_DISK},if=none,id=hd0,format=qcow2,cache=writeback,discard=on"
  -device ide-hd,drive=hd0,bus=sata.0,bootindex=1
  -device ide-cd,drive=cd0,bus=sata.1,bootindex=2
  -drive "file=${WIN_ISO},if=none,id=cd0,media=cdrom"
  -device ide-cd,drive=cd1,bus=sata.2,bootindex=3
  -drive "file=${VIRTIO_ISO},if=none,id=cd1,media=cdrom"
  -netdev "user,id=net0,hostfwd=tcp::${VM_RDP_PORT}-:3389"
  -device "${VM_NET_DEVICE},netdev=net0"
)

if [ "${GPU_USE_VIRTIO_DISPLAY}" = "yes" ]; then
  QEMU_CMD+=( -vga virtio )
else
  QEMU_CMD+=( -vga none )
fi

QEMU_CMD+=(
  -display sdl,gl=on
  -device ich9-intel-hda
  -device hda-duplex
  -usb
  -device usb-tablet
  -device vfio-pci,host="${GPU_HOST_PCI}",x-vga=on
)

if [ -n "${GPU_AUDIO_PCI:-}" ]; then
  QEMU_CMD+=( -device "vfio-pci,host=${GPU_AUDIO_PCI}" )
fi

exec "${QEMU_CMD[@]}"
EOF

chmod +x "$GPU_START_SCRIPT"
echo "Script GPU dibuat di: $GPU_START_SCRIPT"

normalize_grub_cmdline() {
  local line current cleaned backup
  backup="/etc/default/grub.bak.$(date +%Y%m%d-%H%M%S)"
  sudo cp /etc/default/grub "$backup"

  line="$(grep '^GRUB_CMDLINE_LINUX_DEFAULT=' /etc/default/grub | head -n1 || true)"
  if [ -z "$line" ]; then
    echo "GRUB_CMDLINE_LINUX_DEFAULT tidak ditemukan di /etc/default/grub"
    exit 1
  fi

  current="$(printf '%s\n' "$line" | sed -n 's/^GRUB_CMDLINE_LINUX_DEFAULT="\(.*\)"$/\1/p')"
  if [ -z "$current" ]; then
    current="$(printf '%s\n' "$line" | sed -n "s/^GRUB_CMDLINE_LINUX_DEFAULT='\(.*\)'$/\1/p")"
  fi
  if [ -z "$current" ]; then
    current="${line#GRUB_CMDLINE_LINUX_DEFAULT=}"
  fi

  cleaned="$(printf '%s' "$current" | sed -E "s/GRUB_CMDLINE_LINUX_DEFAULT='([^']*)'/\1/g; s/[\"']//g; s/[[:space:]]+/ /g; s/^ //; s/ $//")"
  cleaned="${cleaned//nvidia_drm.modeset=1/}"
  cleaned="${cleaned//intel_iommu=on/}"
  cleaned="${cleaned//iommu=pt/}"
  cleaned="$(printf '%s' "$cleaned" | sed -E 's/[[:space:]]+/ /g; s/^ //; s/ $//')"

  if [ -n "$cleaned" ]; then
    cleaned="$cleaned intel_iommu=on iommu=pt vfio-pci.ids=$GPU_IDS,$GPU_AUDIO_IDS"
  else
    cleaned="intel_iommu=on iommu=pt vfio-pci.ids=$GPU_IDS,$GPU_AUDIO_IDS"
  fi

  sudo sed -i "s|^GRUB_CMDLINE_LINUX_DEFAULT=.*|GRUB_CMDLINE_LINUX_DEFAULT=\"$cleaned\"|" /etc/default/grub
}

update_mkinitcpio_modules() {
  local backup tmp
  backup="/etc/mkinitcpio.conf.bak.$(date +%Y%m%d-%H%M%S)"
  sudo cp /etc/mkinitcpio.conf "$backup"
  tmp="$(mktemp)"

  awk '
    BEGIN {updated=0}
    /^MODULES=/ && !updated {
      if ($0 ~ /vfio_pci/) {
        print
      } else {
        sub(/^MODULES=\(/, "MODULES=(vfio_pci vfio vfio_iommu_type1 ")
        print
      }
      updated=1
      next
    }
    { print }
    END {
      if (!updated) {
        print "MODULES=(vfio_pci vfio vfio_iommu_type1)"
      }
    }
  ' /etc/mkinitcpio.conf > "$tmp"

  sudo cp "$tmp" /etc/mkinitcpio.conf
  rm -f "$tmp"
}

echo "Menulis binding VFIO dan blacklist module..."
cat <<EOF | sudo tee /etc/modprobe.d/winvm-vfio.conf >/dev/null
options vfio-pci ids=$GPU_IDS,$GPU_AUDIO_IDS
EOF

cat <<'EOF' | sudo tee /etc/modprobe.d/winvm-blacklist-nvidia.conf >/dev/null
blacklist nouveau
blacklist nvidia
blacklist nvidia_drm
blacklist nvidia_modeset
blacklist nvidia_uvm
EOF

normalize_grub_cmdline
update_mkinitcpio_modules

echo "Membangun ulang initramfs..."
sudo mkinitcpio -P

echo "Membangun ulang grub.cfg..."
sudo grub-mkconfig -o /boot/grub/grub.cfg

echo
echo "Setup passthrough selesai."
echo "Langkah berikutnya:"
echo "  1. Reboot host Linux."
echo "  2. Jalankan: bash $GPU_START_SCRIPT"
echo "  3. Di Windows guest, install driver NVIDIA setelah boot."
echo
echo "Catatan:"
echo "  - Intel Iris Xe tetap dipakai host."
echo "  - Kalau port HDMI/DP di RTX dipakai host, kemungkinan tidak akan aktif setelah passthrough."
